version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: python -m py_compile stronk/stronk.py
  test:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: python -m unittest test/test_stronk.py
  deploy:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: sudo pip install twine
      - run: python setup.py sdist bdist_wheel
      - run: twine -u brianrthompson -p er)DSDSL-490 upload dist/*
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
  deploy:
    jobs:
      - deploy